import type { Metadata } from "next";
import Body from '@/components/body';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="fr" className={inter.variable} data-scroll-behavior="smooth">
            <Body>
                {children}
            </Body>
        </html>
    );
}
